
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import CustomNavBar from "@/components/customNavbar";
import Footer from "@/components/footer";
import { ToastContainer } from 'react-toastify';

import UserProvider from '@/usecontext/userProvider';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <UserProvider>

           <ToastContainer/>
          <CustomNavBar/>
          {children}

        <Footer/>
        </UserProvider>
          
        
       
      </body>
    </html>
  );
}
